config/routes.rb
Rails.application.routes.draw do
  resources :recurring_events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect("/recurring_events")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recurring_event.rb
class RecurringEvent < ActiveRecord::Base
  validates :name, :start_date, :interval, :day_of_month, presence: true
  validate :day_of_month_is_valid
  validate :interval_is_valid

  LAST_DAYS = { 1 => 31,
                2 => 28,
                3 => 31,
                4 => 30,
                5 => 31,
                6 => 30,
                7 => 31,
                8 => 31,
                9 => 30,
                10 => 31,
                11 => 30,
                12 => 31 }

  def get_next_occurrences(n)
    today = Date.today
    occurrences = []

    month_year_data = is_first_date_less_than_second(today, self.start_date) ? get_next_for_future_starts : get_next_for_past_starts
    month = month_year_data[0]
    year = month_year_data[1]

    end_of_month = self.day_of_month > 28
    day = end_of_month ? LAST_DAYS[month] : self.day_of_month

    (1..n).each do |i|
      occurrence = Date.new(year, month, day)
      occurrence = get_actual_occurrence(occurrence) if is_holiday_or_weekend?(occurrence)
      occurrences << occurrence
      month += self.interval

      until month <= 12
        month -= 12
        year += 1
      end

      day = end_of_month ? LAST_DAYS(day, month) : day
    end

    occurrences
  end

  def get_next_for_future_starts
    first_occurrence = get_first_occurrence
    month = first_occurrence.month
    year = first_occurrence.year
    [month, year]
  end

  def get_next_for_past_starts
    last_occurrence = get_past_occurrences.last
    month = last_occurrence.month + self.interval
    year = last_occurrence.year

    until month <= 12
      month -= 12
      year += 1
    end

    [month, year]
  end


  def get_day_suffix
    case self.day_of_month % 10
      when 1
        return "st"
      when 2
        return "nd"
      when 3
        return "rd"
      else
        return "th"
    end
  end

  def get_past_occurrences
    occurrences = []
    end_of_month = self.day_of_month > 28
    today = Date.today

    occurrence = get_first_occurrence
    year, month, day = occurrence.year, occurrence.month, occurrence.day
    until is_first_date_less_than_second(today, occurrence)
      occurrence = Date.new(year, month, day)
      occurrences << occurrence

      month += self.interval
      until month <= 12
        month -= 12
        year += 1
      end

      day = end_of_month ? LAST_DAYS[month] : day
    end

    occurrences.pop
    occurrences
  end

  def get_first_occurrence
    year = self.start_date.year
    month = self.start_date.month
    day = self.day_of_month

    if self.start_date.day > day
      month += 1
    end

    until month <= 12
      month -= 12
      year += 1
    end

    Date.new(year, month, day)
  end

  def is_first_date_less_than_second(date1, date2)
    return false unless date1 && date2
    date1 < date2
  end

  def is_holiday_or_weekend?(date)
    return true if date.saturday? || date.sunday?

    case date.month
      when 1
        return true if date.day == 1
        return true if date.monday? && date.day/7 == 2
      when 2
        return true if date.monday? && date.day/7 == 2
      when 5
        return true if date.monday? && date.day/7 == 4
      when 7
        return true if date.day == 4
      when 9
        return true if date.monday? && date.day/7 == 0
      when 10
        return true if date.monday? && date.day/7 == 0
      when 11
        return true if date.thursday? && date.day/7 == 3
      when 12
        return true if date.day == 25
      else
        return false
    end
  end

  # def get_last_day_of_month(day, month)
  #   last_days = { 1 => 31,
  #                 2 => 28,
  #                 3 => 31,
  #                 4 => 30,
  #                 5 => 31,
  #                 6 => 30,
  #                 7 => 31,
  #                 8 => 31,
  #                 9 => 30,
  #                 10 => 31,
  #                 11 => 30,
  #                 12 => 31 }
  #
  #   last_days[month]
  # end

  def get_actual_occurrence(date)
    year = date.year
    month = date.month
    day = date.day

    while is_holiday_or_weekend?(date)
      day = day - 1
      if day < 1
        month = month - 1
        day = LAST_DAYS[month]
      end

      if month < 1
        year = year - 1
      end

      date = Date.new(year, month, day)
    end

    date
  end

  def future_start_date
    errors.add(:start_date, "Start date cannot be in the past") unless is_first_date_less_than_second(Date.today, self.start_date)
  end

  def interval_is_valid
    errors.add(:interval, "There must be at least 1 month between occurrences.") unless self.interval && self.interval > 0
  end

  def day_of_month_is_valid
    errors.add(:day_of_month, "Invalid day of month.") unless self.day_of_month && (self.day_of_month > 0 && self.day_of_month < 32)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recurring_events_controller.rb
class RecurringEventsController < ApplicationController
  def index
    @recurring_events = RecurringEvent.all
  end

  def create
    @recurring_event = RecurringEvent.new(event_params)

    if @recurring_event.save
      redirect_to :root
    else
      flash.now[:errors] = @recurring_event.errors.full_messages
      render :new
    end
  end

  def new
  end

  def show
    @recurring_event = RecurringEvent.find(params[:id])
  end

  def edit
    @recurring_event = RecurringEvent.find(params[:id])
  end

  def update
    @recurring_event = RecurringEvent.find(params[:id])

    if @recurring_event.update(event_params)
      redirect_to @recurring_event
    else
      flash.now[:errors] = @recurring_event.errors.full_messages
      render :edit
    end
  end

  def destroy
    @recurring_event = RecurringEvent.find(params[:id])
    @recurring_event.destroy!
    redirect_to :root
  end

  private
  def event_params
    params.require(:recurring_event).permit(:name, :start_date, :interval, :buffer, :day_of_month)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TLFChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recurring_events/_form.html.erb
<% button_text = action_type == :new ? "Create event!" : "Update event" %>
<% action_url = action_type == :new ? recurring_events_url : recurring_event_url(recurring_event) %>

<form class="event-form" action="<%= action_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">

  <label>
    Event name:
    <input type="text" name="recurring_event[name]" value="<%= recurring_event.name %>">
  </label>

  <hr />

  <label>
    Start date:
    <input type="date" name="recurring_event[start_date]" value="<%= recurring_event.start_date %>">
  </label>

  <hr />

  <label>
    Day of month:
    <input type="number" min=1 max=31 name="recurring_event[day_of_month]" value="<%= recurring_event.day_of_month %>">
  </label>

  <hr />

  <label>
    Months between occurrences:
    <input type="number" min=0 name="recurring_event[interval]" value="<%= recurring_event.interval %>">
  </label>

  <hr />

  <!-- <label>
    Buffer days:
    <input type="number" min=0 name="recurring_event[buffer]" value="<%= @recurring_event.buffer %>">
  </label> -->

  <hr />

  <input type="submit" name="" value="<%= button_text %>">
</form>

app/views/recurring_events/edit.html.erb
<% action_url = '/recurring_events/' + @recurring_event.id.to_s %>

<h2>Edit this event</h2>

<% if flash.now[:errors] %>
  <ul>
    <% flash.now[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>


<%= render 'form', action_type: :update, recurring_event: @recurring_event %>

<%= button_to "Delete this event forever!", recurring_event_url(@recurring_event), method: :delete %>

app/views/recurring_events/index.html.erb
<h1>Recurring Events!</h1>
<div class="index-container">
  <ul>
    <% @recurring_events.each do |event| %>
      <% edit_url = '/recurring_events/' + event.id.to_s + '/edit' %>
      <li>
        <div><b><%= link_to event.name, event %></b></div>
        <div><%= link_to "Edit or delete", edit_url %></div>
        <div>Next occurrence: <%= event.get_next_occurrences(1).first %></div>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to 'Make an event!', new_recurring_event_url %>

app/views/recurring_events/new.html.erb
<h2>Make a new event!</h2>

<form class="event-form" action="<%= recurring_events_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Event name:
    <input type="text" name="recurring_event[name]" value="">
  </label>
  <hr />
  <label>
    Start date:
    <input type="date" name="recurring_event[start_date]" value="">
  </label>
  <hr />
  <label>
    Day of month:
    <input type="number" min=1 max=31 name="recurring_event[day_of_month]" value="">
  </label>
  <hr />
  <label>
    Months between occurrences:
    <input type="number" min=1 name="recurring_event[interval]" value="">
  </label>
  <hr />
  <!-- <label>
    Buffer days:
    <input type="number" min=0 name="recurring_event[buffer]" value="">
  </label> -->
  <hr />
  <input type="submit" name="" value="Save event">
</form>

app/views/recurring_events/show.html.erb
<h2><%= @recurring_event.name %></h2>

<div class="event-info">
  This event occurs every <%= @recurring_event.interval %> months on the <%= @recurring_event.day_of_month %><%= @recurring_event.get_day_suffix %> of the month.
</div>

<div>
  The next four occurrences will be:
  <ul>
    <% occurrences = @recurring_event.get_next_occurrences(4) %>
    <% occurrences.each do |occurrence| %>
      <li><%= occurrence %></li>
    <% end %>
  </ul>
</div>